Repository dead-space-server/space-station-14-soyuz, pull requests merged in 2025-07, with the labels that each got.

#7 [FIX] Фиксы теста
  Content.IntegrationTests/Tests/PostMapInitTest.cs
  Resources/Audio/Jukebox/attributions.yml
  Resources/Maps/cluster.yml
  Resources/Maps/ds_aspid.yml
  Resources/Maps/ds_silly.yml
  Resources/Maps/omega.yml
  Resources/Maps/packed.yml
  Resources/Maps/saltern.yml
  Resources/Prototypes/Maps/aspid.yml
  Resources/Prototypes/Maps/cluster.yml
  Resources/Prototypes/Maps/silly.yml
Labels: Changes: C#, Changes: Map, Changes: No C#, S: Approved, size/XL

#5 Автозамены
  Resources/Locale/ru-RU/_deadspace/speech/speech-chatsan.ftl
Labels: Changes: Localization, Changes: No C#, S: Approved

#9 Много исправлений локализации
  Resources/Locale/ru-RU/_deadspace/prototypes/entities/objects/weapons/guns/battery/pistol-mini.ftl
  Resources/Locale/ru-RU/_deadspace/prototypes/entities/other/ertloadouts.ftl
  Resources/Locale/ru-RU/delivery/delivery-spam.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/lockers/suit_storage.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/markers/spawners/random/department/security.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/structures/machines/holopad.ftl
  Resources/Prototypes/_DeadSpace/Entities/Clothing/Underwear/socks.yml
Labels: size/S, Changes: Localization, Changes: No C#, S: Approved

#6 Патроны 5.45
  Resources/Prototypes/_DeadSpace/Soyuz/Entities/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.yml
  Resources/Prototypes/_DeadSpace/Soyuz/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/lightest_rifle.yml
  Resources/Prototypes/_DeadSpace/Soyuz/Entities/Objects/Weapons/Guns/Ammunition/Projectiles/lightest_rifle.yml
  Resources/Prototypes/_DeadSpace/tags.yml
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/base.png
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/incendiary.png
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/mag-1.png
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/mag-2.png
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/mag-3.png
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/meta.json
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/practice.png
  Resources/Textures/_DeadSpace/Objects/Weapons/Guns/Ammunition/Boxes/lightest_rifle.rsi/uranium.png
Labels: Changes: No C#, Changes: Sprites, S: Approved, size/M

#14 [FIX] Фикс Теста No2
  Resources/Prototypes/_DeadSpace/Loadouts/Jobs/Command/officer_blue_shield.yml
  Resources/Prototypes/_DeadSpace/Loadouts/loadout_groups.yml
Labels: size/S, Changes: No C#, S: Approved

#15 Изменения локализации
  Resources/Locale/ru-RU/_adt/prototypes/entities/clothing/outerclothing/veteransechardsuit.ftl
  Resources/Locale/ru-RU/_deadspace/prototypes/entities/objects/misc/bedsheets.ftl
  Resources/Locale/ru-RU/job/job-names.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/catalog/fills/boxes/emergency.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/misc/pen.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/tools/access_breaker.ftl
Labels: size/S, Changes: Localization, Changes: No C#, S: Approved
